(cl:defpackage dashgo_tools-msg
  (:use )
  (:export
   "<CHECK_MSGACTION>"
   "CHECK_MSGACTION"
   "<CHECK_MSGACTIONFEEDBACK>"
   "CHECK_MSGACTIONFEEDBACK"
   "<CHECK_MSGACTIONGOAL>"
   "CHECK_MSGACTIONGOAL"
   "<CHECK_MSGACTIONRESULT>"
   "CHECK_MSGACTIONRESULT"
   "<CHECK_MSGFEEDBACK>"
   "CHECK_MSGFEEDBACK"
   "<CHECK_MSGGOAL>"
   "CHECK_MSGGOAL"
   "<CHECK_MSGRESULT>"
   "CHECK_MSGRESULT"
  ))

