; Auto-generated. Do not edit!


(cl:in-package dashgo_tools-msg)


;//! \htmlinclude check_msgResult.msg.html

(cl:defclass <check_msgResult> (roslisp-msg-protocol:ros-message)
  ((issuccess
    :reader issuccess
    :initarg :issuccess
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass check_msgResult (<check_msgResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <check_msgResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'check_msgResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dashgo_tools-msg:<check_msgResult> is deprecated: use dashgo_tools-msg:check_msgResult instead.")))

(cl:ensure-generic-function 'issuccess-val :lambda-list '(m))
(cl:defmethod issuccess-val ((m <check_msgResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dashgo_tools-msg:issuccess-val is deprecated.  Use dashgo_tools-msg:issuccess instead.")
  (issuccess m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <check_msgResult>) ostream)
  "Serializes a message object of type '<check_msgResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'issuccess) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <check_msgResult>) istream)
  "Deserializes a message object of type '<check_msgResult>"
    (cl:setf (cl:slot-value msg 'issuccess) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<check_msgResult>)))
  "Returns string type for a message object of type '<check_msgResult>"
  "dashgo_tools/check_msgResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'check_msgResult)))
  "Returns string type for a message object of type 'check_msgResult"
  "dashgo_tools/check_msgResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<check_msgResult>)))
  "Returns md5sum for a message object of type '<check_msgResult>"
  "e40869114e279d3e4fa137fdad5acd7d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'check_msgResult)))
  "Returns md5sum for a message object of type 'check_msgResult"
  "e40869114e279d3e4fa137fdad5acd7d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<check_msgResult>)))
  "Returns full string definition for message of type '<check_msgResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool issuccess~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'check_msgResult)))
  "Returns full string definition for message of type 'check_msgResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool issuccess~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <check_msgResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <check_msgResult>))
  "Converts a ROS message object to a list"
  (cl:list 'check_msgResult
    (cl:cons ':issuccess (issuccess msg))
))
