; Auto-generated. Do not edit!


(cl:in-package dashgo_tools-msg)


;//! \htmlinclude check_msgFeedback.msg.html

(cl:defclass <check_msgFeedback> (roslisp-msg-protocol:ros-message)
  ((accomplished
    :reader accomplished
    :initarg :accomplished
    :type cl:float
    :initform 0.0))
)

(cl:defclass check_msgFeedback (<check_msgFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <check_msgFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'check_msgFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dashgo_tools-msg:<check_msgFeedback> is deprecated: use dashgo_tools-msg:check_msgFeedback instead.")))

(cl:ensure-generic-function 'accomplished-val :lambda-list '(m))
(cl:defmethod accomplished-val ((m <check_msgFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dashgo_tools-msg:accomplished-val is deprecated.  Use dashgo_tools-msg:accomplished instead.")
  (accomplished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <check_msgFeedback>) ostream)
  "Serializes a message object of type '<check_msgFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'accomplished))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <check_msgFeedback>) istream)
  "Deserializes a message object of type '<check_msgFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'accomplished) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<check_msgFeedback>)))
  "Returns string type for a message object of type '<check_msgFeedback>"
  "dashgo_tools/check_msgFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'check_msgFeedback)))
  "Returns string type for a message object of type 'check_msgFeedback"
  "dashgo_tools/check_msgFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<check_msgFeedback>)))
  "Returns md5sum for a message object of type '<check_msgFeedback>"
  "00dcf0d5008205d95b1f8016ae205cce")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'check_msgFeedback)))
  "Returns md5sum for a message object of type 'check_msgFeedback"
  "00dcf0d5008205d95b1f8016ae205cce")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<check_msgFeedback>)))
  "Returns full string definition for message of type '<check_msgFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 accomplished~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'check_msgFeedback)))
  "Returns full string definition for message of type 'check_msgFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 accomplished~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <check_msgFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <check_msgFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'check_msgFeedback
    (cl:cons ':accomplished (accomplished msg))
))
