// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/pose_graph.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping/proto/trajectory.pb.h"
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping {
namespace proto {
class NodeId;
class NodeIdDefaultTypeInternal;
extern NodeIdDefaultTypeInternal _NodeId_default_instance_;
class PoseGraph;
class PoseGraphDefaultTypeInternal;
extern PoseGraphDefaultTypeInternal _PoseGraph_default_instance_;
class PoseGraph_Constraint;
class PoseGraph_ConstraintDefaultTypeInternal;
extern PoseGraph_ConstraintDefaultTypeInternal _PoseGraph_Constraint_default_instance_;
class SubmapId;
class SubmapIdDefaultTypeInternal;
extern SubmapIdDefaultTypeInternal _SubmapId_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

namespace cartographer {
namespace mapping {
namespace proto {

namespace protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto

enum PoseGraph_Constraint_Tag {
  PoseGraph_Constraint_Tag_INTRA_SUBMAP = 0,
  PoseGraph_Constraint_Tag_INTER_SUBMAP = 1,
  PoseGraph_Constraint_Tag_PoseGraph_Constraint_Tag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PoseGraph_Constraint_Tag_PoseGraph_Constraint_Tag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PoseGraph_Constraint_Tag_IsValid(int value);
const PoseGraph_Constraint_Tag PoseGraph_Constraint_Tag_Tag_MIN = PoseGraph_Constraint_Tag_INTRA_SUBMAP;
const PoseGraph_Constraint_Tag PoseGraph_Constraint_Tag_Tag_MAX = PoseGraph_Constraint_Tag_INTER_SUBMAP;
const int PoseGraph_Constraint_Tag_Tag_ARRAYSIZE = PoseGraph_Constraint_Tag_Tag_MAX + 1;

const ::google::protobuf::EnumDescriptor* PoseGraph_Constraint_Tag_descriptor();
inline const ::std::string& PoseGraph_Constraint_Tag_Name(PoseGraph_Constraint_Tag value) {
  return ::google::protobuf::internal::NameOfEnum(
    PoseGraph_Constraint_Tag_descriptor(), value);
}
inline bool PoseGraph_Constraint_Tag_Parse(
    const ::std::string& name, PoseGraph_Constraint_Tag* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PoseGraph_Constraint_Tag>(
    PoseGraph_Constraint_Tag_descriptor(), name, value);
}
// ===================================================================

class SubmapId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.SubmapId) */ {
 public:
  SubmapId();
  virtual ~SubmapId();

  SubmapId(const SubmapId& from);

  inline SubmapId& operator=(const SubmapId& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SubmapId(SubmapId&& from) noexcept
    : SubmapId() {
    *this = ::std::move(from);
  }

  inline SubmapId& operator=(SubmapId&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SubmapId& default_instance();

  static inline const SubmapId* internal_default_instance() {
    return reinterpret_cast<const SubmapId*>(
               &_SubmapId_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SubmapId* other);
  friend void swap(SubmapId& a, SubmapId& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SubmapId* New() const PROTOBUF_FINAL { return New(NULL); }

  SubmapId* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SubmapId& from);
  void MergeFrom(const SubmapId& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SubmapId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // int32 submap_index = 2;
  void clear_submap_index();
  static const int kSubmapIndexFieldNumber = 2;
  ::google::protobuf::int32 submap_index() const;
  void set_submap_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SubmapId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 trajectory_id_;
  ::google::protobuf::int32 submap_index_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NodeId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.NodeId) */ {
 public:
  NodeId();
  virtual ~NodeId();

  NodeId(const NodeId& from);

  inline NodeId& operator=(const NodeId& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NodeId(NodeId&& from) noexcept
    : NodeId() {
    *this = ::std::move(from);
  }

  inline NodeId& operator=(NodeId&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeId& default_instance();

  static inline const NodeId* internal_default_instance() {
    return reinterpret_cast<const NodeId*>(
               &_NodeId_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NodeId* other);
  friend void swap(NodeId& a, NodeId& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NodeId* New() const PROTOBUF_FINAL { return New(NULL); }

  NodeId* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NodeId& from);
  void MergeFrom(const NodeId& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NodeId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // int32 node_index = 2;
  void clear_node_index();
  static const int kNodeIndexFieldNumber = 2;
  ::google::protobuf::int32 node_index() const;
  void set_node_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.NodeId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 trajectory_id_;
  ::google::protobuf::int32 node_index_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PoseGraph_Constraint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.PoseGraph.Constraint) */ {
 public:
  PoseGraph_Constraint();
  virtual ~PoseGraph_Constraint();

  PoseGraph_Constraint(const PoseGraph_Constraint& from);

  inline PoseGraph_Constraint& operator=(const PoseGraph_Constraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PoseGraph_Constraint(PoseGraph_Constraint&& from) noexcept
    : PoseGraph_Constraint() {
    *this = ::std::move(from);
  }

  inline PoseGraph_Constraint& operator=(PoseGraph_Constraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PoseGraph_Constraint& default_instance();

  static inline const PoseGraph_Constraint* internal_default_instance() {
    return reinterpret_cast<const PoseGraph_Constraint*>(
               &_PoseGraph_Constraint_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PoseGraph_Constraint* other);
  friend void swap(PoseGraph_Constraint& a, PoseGraph_Constraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PoseGraph_Constraint* New() const PROTOBUF_FINAL { return New(NULL); }

  PoseGraph_Constraint* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PoseGraph_Constraint& from);
  void MergeFrom(const PoseGraph_Constraint& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PoseGraph_Constraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef PoseGraph_Constraint_Tag Tag;
  static const Tag INTRA_SUBMAP =
    PoseGraph_Constraint_Tag_INTRA_SUBMAP;
  static const Tag INTER_SUBMAP =
    PoseGraph_Constraint_Tag_INTER_SUBMAP;
  static inline bool Tag_IsValid(int value) {
    return PoseGraph_Constraint_Tag_IsValid(value);
  }
  static const Tag Tag_MIN =
    PoseGraph_Constraint_Tag_Tag_MIN;
  static const Tag Tag_MAX =
    PoseGraph_Constraint_Tag_Tag_MAX;
  static const int Tag_ARRAYSIZE =
    PoseGraph_Constraint_Tag_Tag_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Tag_descriptor() {
    return PoseGraph_Constraint_Tag_descriptor();
  }
  static inline const ::std::string& Tag_Name(Tag value) {
    return PoseGraph_Constraint_Tag_Name(value);
  }
  static inline bool Tag_Parse(const ::std::string& name,
      Tag* value) {
    return PoseGraph_Constraint_Tag_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .cartographer.mapping.proto.SubmapId submap_id = 1;
  bool has_submap_id() const;
  void clear_submap_id();
  static const int kSubmapIdFieldNumber = 1;
  const ::cartographer::mapping::proto::SubmapId& submap_id() const;
  ::cartographer::mapping::proto::SubmapId* mutable_submap_id();
  ::cartographer::mapping::proto::SubmapId* release_submap_id();
  void set_allocated_submap_id(::cartographer::mapping::proto::SubmapId* submap_id);

  // .cartographer.mapping.proto.NodeId node_id = 2;
  bool has_node_id() const;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 2;
  const ::cartographer::mapping::proto::NodeId& node_id() const;
  ::cartographer::mapping::proto::NodeId* mutable_node_id();
  ::cartographer::mapping::proto::NodeId* release_node_id();
  void set_allocated_node_id(::cartographer::mapping::proto::NodeId* node_id);

  // .cartographer.transform.proto.Rigid3d relative_pose = 3;
  bool has_relative_pose() const;
  void clear_relative_pose();
  static const int kRelativePoseFieldNumber = 3;
  const ::cartographer::transform::proto::Rigid3d& relative_pose() const;
  ::cartographer::transform::proto::Rigid3d* mutable_relative_pose();
  ::cartographer::transform::proto::Rigid3d* release_relative_pose();
  void set_allocated_relative_pose(::cartographer::transform::proto::Rigid3d* relative_pose);

  // double translation_weight = 6;
  void clear_translation_weight();
  static const int kTranslationWeightFieldNumber = 6;
  double translation_weight() const;
  void set_translation_weight(double value);

  // double rotation_weight = 7;
  void clear_rotation_weight();
  static const int kRotationWeightFieldNumber = 7;
  double rotation_weight() const;
  void set_rotation_weight(double value);

  // .cartographer.mapping.proto.PoseGraph.Constraint.Tag tag = 5;
  void clear_tag();
  static const int kTagFieldNumber = 5;
  ::cartographer::mapping::proto::PoseGraph_Constraint_Tag tag() const;
  void set_tag(::cartographer::mapping::proto::PoseGraph_Constraint_Tag value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseGraph.Constraint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::mapping::proto::SubmapId* submap_id_;
  ::cartographer::mapping::proto::NodeId* node_id_;
  ::cartographer::transform::proto::Rigid3d* relative_pose_;
  double translation_weight_;
  double rotation_weight_;
  int tag_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PoseGraph : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.PoseGraph) */ {
 public:
  PoseGraph();
  virtual ~PoseGraph();

  PoseGraph(const PoseGraph& from);

  inline PoseGraph& operator=(const PoseGraph& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PoseGraph(PoseGraph&& from) noexcept
    : PoseGraph() {
    *this = ::std::move(from);
  }

  inline PoseGraph& operator=(PoseGraph&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PoseGraph& default_instance();

  static inline const PoseGraph* internal_default_instance() {
    return reinterpret_cast<const PoseGraph*>(
               &_PoseGraph_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PoseGraph* other);
  friend void swap(PoseGraph& a, PoseGraph& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PoseGraph* New() const PROTOBUF_FINAL { return New(NULL); }

  PoseGraph* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PoseGraph& from);
  void MergeFrom(const PoseGraph& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PoseGraph* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef PoseGraph_Constraint Constraint;

  // accessors -------------------------------------------------------

  // repeated .cartographer.mapping.proto.PoseGraph.Constraint constraint = 2;
  int constraint_size() const;
  void clear_constraint();
  static const int kConstraintFieldNumber = 2;
  const ::cartographer::mapping::proto::PoseGraph_Constraint& constraint(int index) const;
  ::cartographer::mapping::proto::PoseGraph_Constraint* mutable_constraint(int index);
  ::cartographer::mapping::proto::PoseGraph_Constraint* add_constraint();
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::PoseGraph_Constraint >*
      mutable_constraint();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::PoseGraph_Constraint >&
      constraint() const;

  // repeated .cartographer.mapping.proto.Trajectory trajectory = 4;
  int trajectory_size() const;
  void clear_trajectory();
  static const int kTrajectoryFieldNumber = 4;
  const ::cartographer::mapping::proto::Trajectory& trajectory(int index) const;
  ::cartographer::mapping::proto::Trajectory* mutable_trajectory(int index);
  ::cartographer::mapping::proto::Trajectory* add_trajectory();
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Trajectory >*
      mutable_trajectory();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Trajectory >&
      trajectory() const;

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseGraph)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::PoseGraph_Constraint > constraint_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Trajectory > trajectory_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SubmapId

// int32 trajectory_id = 1;
inline void SubmapId::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 SubmapId::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SubmapId.trajectory_id)
  return trajectory_id_;
}
inline void SubmapId::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.SubmapId.trajectory_id)
}

// int32 submap_index = 2;
inline void SubmapId::clear_submap_index() {
  submap_index_ = 0;
}
inline ::google::protobuf::int32 SubmapId::submap_index() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SubmapId.submap_index)
  return submap_index_;
}
inline void SubmapId::set_submap_index(::google::protobuf::int32 value) {
  
  submap_index_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.SubmapId.submap_index)
}

// -------------------------------------------------------------------

// NodeId

// int32 trajectory_id = 1;
inline void NodeId::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 NodeId::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.NodeId.trajectory_id)
  return trajectory_id_;
}
inline void NodeId::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.NodeId.trajectory_id)
}

// int32 node_index = 2;
inline void NodeId::clear_node_index() {
  node_index_ = 0;
}
inline ::google::protobuf::int32 NodeId::node_index() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.NodeId.node_index)
  return node_index_;
}
inline void NodeId::set_node_index(::google::protobuf::int32 value) {
  
  node_index_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.NodeId.node_index)
}

// -------------------------------------------------------------------

// PoseGraph_Constraint

// .cartographer.mapping.proto.SubmapId submap_id = 1;
inline bool PoseGraph_Constraint::has_submap_id() const {
  return this != internal_default_instance() && submap_id_ != NULL;
}
inline void PoseGraph_Constraint::clear_submap_id() {
  if (GetArenaNoVirtual() == NULL && submap_id_ != NULL) delete submap_id_;
  submap_id_ = NULL;
}
inline const ::cartographer::mapping::proto::SubmapId& PoseGraph_Constraint::submap_id() const {
  const ::cartographer::mapping::proto::SubmapId* p = submap_id_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.submap_id)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::SubmapId*>(
      &::cartographer::mapping::proto::_SubmapId_default_instance_);
}
inline ::cartographer::mapping::proto::SubmapId* PoseGraph_Constraint::mutable_submap_id() {
  
  if (submap_id_ == NULL) {
    submap_id_ = new ::cartographer::mapping::proto::SubmapId;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseGraph.Constraint.submap_id)
  return submap_id_;
}
inline ::cartographer::mapping::proto::SubmapId* PoseGraph_Constraint::release_submap_id() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.PoseGraph.Constraint.submap_id)
  
  ::cartographer::mapping::proto::SubmapId* temp = submap_id_;
  submap_id_ = NULL;
  return temp;
}
inline void PoseGraph_Constraint::set_allocated_submap_id(::cartographer::mapping::proto::SubmapId* submap_id) {
  delete submap_id_;
  submap_id_ = submap_id;
  if (submap_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.PoseGraph.Constraint.submap_id)
}

// .cartographer.mapping.proto.NodeId node_id = 2;
inline bool PoseGraph_Constraint::has_node_id() const {
  return this != internal_default_instance() && node_id_ != NULL;
}
inline void PoseGraph_Constraint::clear_node_id() {
  if (GetArenaNoVirtual() == NULL && node_id_ != NULL) delete node_id_;
  node_id_ = NULL;
}
inline const ::cartographer::mapping::proto::NodeId& PoseGraph_Constraint::node_id() const {
  const ::cartographer::mapping::proto::NodeId* p = node_id_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.node_id)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::NodeId*>(
      &::cartographer::mapping::proto::_NodeId_default_instance_);
}
inline ::cartographer::mapping::proto::NodeId* PoseGraph_Constraint::mutable_node_id() {
  
  if (node_id_ == NULL) {
    node_id_ = new ::cartographer::mapping::proto::NodeId;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseGraph.Constraint.node_id)
  return node_id_;
}
inline ::cartographer::mapping::proto::NodeId* PoseGraph_Constraint::release_node_id() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.PoseGraph.Constraint.node_id)
  
  ::cartographer::mapping::proto::NodeId* temp = node_id_;
  node_id_ = NULL;
  return temp;
}
inline void PoseGraph_Constraint::set_allocated_node_id(::cartographer::mapping::proto::NodeId* node_id) {
  delete node_id_;
  node_id_ = node_id;
  if (node_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.PoseGraph.Constraint.node_id)
}

// .cartographer.transform.proto.Rigid3d relative_pose = 3;
inline bool PoseGraph_Constraint::has_relative_pose() const {
  return this != internal_default_instance() && relative_pose_ != NULL;
}
inline void PoseGraph_Constraint::clear_relative_pose() {
  if (GetArenaNoVirtual() == NULL && relative_pose_ != NULL) delete relative_pose_;
  relative_pose_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& PoseGraph_Constraint::relative_pose() const {
  const ::cartographer::transform::proto::Rigid3d* p = relative_pose_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.relative_pose)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* PoseGraph_Constraint::mutable_relative_pose() {
  
  if (relative_pose_ == NULL) {
    relative_pose_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseGraph.Constraint.relative_pose)
  return relative_pose_;
}
inline ::cartographer::transform::proto::Rigid3d* PoseGraph_Constraint::release_relative_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.PoseGraph.Constraint.relative_pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = relative_pose_;
  relative_pose_ = NULL;
  return temp;
}
inline void PoseGraph_Constraint::set_allocated_relative_pose(::cartographer::transform::proto::Rigid3d* relative_pose) {
  delete relative_pose_;
  relative_pose_ = relative_pose;
  if (relative_pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.PoseGraph.Constraint.relative_pose)
}

// double translation_weight = 6;
inline void PoseGraph_Constraint::clear_translation_weight() {
  translation_weight_ = 0;
}
inline double PoseGraph_Constraint::translation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.translation_weight)
  return translation_weight_;
}
inline void PoseGraph_Constraint::set_translation_weight(double value) {
  
  translation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.PoseGraph.Constraint.translation_weight)
}

// double rotation_weight = 7;
inline void PoseGraph_Constraint::clear_rotation_weight() {
  rotation_weight_ = 0;
}
inline double PoseGraph_Constraint::rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.rotation_weight)
  return rotation_weight_;
}
inline void PoseGraph_Constraint::set_rotation_weight(double value) {
  
  rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.PoseGraph.Constraint.rotation_weight)
}

// .cartographer.mapping.proto.PoseGraph.Constraint.Tag tag = 5;
inline void PoseGraph_Constraint::clear_tag() {
  tag_ = 0;
}
inline ::cartographer::mapping::proto::PoseGraph_Constraint_Tag PoseGraph_Constraint::tag() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.Constraint.tag)
  return static_cast< ::cartographer::mapping::proto::PoseGraph_Constraint_Tag >(tag_);
}
inline void PoseGraph_Constraint::set_tag(::cartographer::mapping::proto::PoseGraph_Constraint_Tag value) {
  
  tag_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.PoseGraph.Constraint.tag)
}

// -------------------------------------------------------------------

// PoseGraph

// repeated .cartographer.mapping.proto.PoseGraph.Constraint constraint = 2;
inline int PoseGraph::constraint_size() const {
  return constraint_.size();
}
inline void PoseGraph::clear_constraint() {
  constraint_.Clear();
}
inline const ::cartographer::mapping::proto::PoseGraph_Constraint& PoseGraph::constraint(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.constraint)
  return constraint_.Get(index);
}
inline ::cartographer::mapping::proto::PoseGraph_Constraint* PoseGraph::mutable_constraint(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseGraph.constraint)
  return constraint_.Mutable(index);
}
inline ::cartographer::mapping::proto::PoseGraph_Constraint* PoseGraph::add_constraint() {
  // @@protoc_insertion_point(field_add:cartographer.mapping.proto.PoseGraph.constraint)
  return constraint_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::PoseGraph_Constraint >*
PoseGraph::mutable_constraint() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.mapping.proto.PoseGraph.constraint)
  return &constraint_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::PoseGraph_Constraint >&
PoseGraph::constraint() const {
  // @@protoc_insertion_point(field_list:cartographer.mapping.proto.PoseGraph.constraint)
  return constraint_;
}

// repeated .cartographer.mapping.proto.Trajectory trajectory = 4;
inline int PoseGraph::trajectory_size() const {
  return trajectory_.size();
}
inline void PoseGraph::clear_trajectory() {
  trajectory_.Clear();
}
inline const ::cartographer::mapping::proto::Trajectory& PoseGraph::trajectory(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseGraph.trajectory)
  return trajectory_.Get(index);
}
inline ::cartographer::mapping::proto::Trajectory* PoseGraph::mutable_trajectory(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseGraph.trajectory)
  return trajectory_.Mutable(index);
}
inline ::cartographer::mapping::proto::Trajectory* PoseGraph::add_trajectory() {
  // @@protoc_insertion_point(field_add:cartographer.mapping.proto.PoseGraph.trajectory)
  return trajectory_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Trajectory >*
PoseGraph::mutable_trajectory() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.mapping.proto.PoseGraph.trajectory)
  return &trajectory_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Trajectory >&
PoseGraph::trajectory() const {
  // @@protoc_insertion_point(field_list:cartographer.mapping.proto.PoseGraph.trajectory)
  return trajectory_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cartographer::mapping::proto::PoseGraph_Constraint_Tag> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cartographer::mapping::proto::PoseGraph_Constraint_Tag>() {
  return ::cartographer::mapping::proto::PoseGraph_Constraint_Tag_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fgraph_2eproto__INCLUDED
