// Auto-generated. Do not edit!

// (in-package dashgo_tools.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class check_msgResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.issuccess = null;
    }
    else {
      if (initObj.hasOwnProperty('issuccess')) {
        this.issuccess = initObj.issuccess
      }
      else {
        this.issuccess = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type check_msgResult
    // Serialize message field [issuccess]
    bufferOffset = _serializer.bool(obj.issuccess, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type check_msgResult
    let len;
    let data = new check_msgResult(null);
    // Deserialize message field [issuccess]
    data.issuccess = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dashgo_tools/check_msgResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e40869114e279d3e4fa137fdad5acd7d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    bool issuccess
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new check_msgResult(null);
    if (msg.issuccess !== undefined) {
      resolved.issuccess = msg.issuccess;
    }
    else {
      resolved.issuccess = false
    }

    return resolved;
    }
};

module.exports = check_msgResult;
